### List all messages
GET http://localhost:8000/messages

### Create a new message
POST http://localhost:8000/messages
content-type: application/json

{
  "content": "123",
  "test": "23"
}

### Get a particular message
GET http://localhost:8000/messages/954